#!/usr/bin/env bash
set -euo pipefail

: "${GOOGLE_CLOUD_PROJECT:?Set GOOGLE_CLOUD_PROJECT}"
: "${GCS_BUCKET:?Set GCS_BUCKET}"
: "${MONGO_URI:?Set MONGO_URI}"

scripts/check-cloud-run-config.sh

REGION="${REGION:-us-central1}"
SERVICE="${SERVICE:-wheatee-api}"
MONGO_DB_NAME="${MONGO_DB_NAME:-wheatee}"
VERTEX_LOCATION="${VERTEX_LOCATION:-us-central1}"
SPEECH_LOCATION="${SPEECH_LOCATION:-global}"
SPEECH_RECOGNIZER="${SPEECH_RECOGNIZER:-_}"
SPEECH_MODEL="${SPEECH_MODEL:-chirp_3}"
SPEECH_LANGUAGE_CODES="${SPEECH_LANGUAGE_CODES:-ur-PK,en-US}"
ENV_VARS="^|^NODE_ENV=production|VERTEX_PROJECT_ID=$GOOGLE_CLOUD_PROJECT|VERTEX_LOCATION=$VERTEX_LOCATION|SPEECH_PROJECT_ID=$GOOGLE_CLOUD_PROJECT|SPEECH_LOCATION=$SPEECH_LOCATION|SPEECH_RECOGNIZER=$SPEECH_RECOGNIZER|SPEECH_MODEL=$SPEECH_MODEL|SPEECH_LANGUAGE_CODES=$SPEECH_LANGUAGE_CODES|GCS_BUCKET=$GCS_BUCKET|MONGO_DB_NAME=$MONGO_DB_NAME|MONGO_URI=$MONGO_URI"

gcloud run deploy "$SERVICE" \
  --source . \
  --project "$GOOGLE_CLOUD_PROJECT" \
  --region "$REGION" \
  --allow-unauthenticated \
  --set-env-vars "$ENV_VARS"
