#!/usr/bin/env bash
set -euo pipefail

: "${GOOGLE_CLOUD_PROJECT:?Set GOOGLE_CLOUD_PROJECT}"
: "${GCS_BUCKET:?Set GCS_BUCKET}"
: "${SUPABASE_URL:?Set SUPABASE_URL}"
: "${SUPABASE_SERVICE_ROLE_KEY_SECRET:?Set SUPABASE_SERVICE_ROLE_KEY_SECRET}"
: "${FIREBASE_SERVICE_ACCOUNT_JSON_SECRET:?Set FIREBASE_SERVICE_ACCOUNT_JSON_SECRET}"

scripts/check-cloud-run-config.sh

REGION="${REGION:-us-central1}"
SERVICE="${SERVICE:-wheaty-api}"
MONGO_DB_NAME="${MONGO_DB_NAME:-wheaty}"
VERTEX_LOCATION="${VERTEX_LOCATION:-us-central1}"
SPEECH_LOCATION="${SPEECH_LOCATION:-global}"
SPEECH_RECOGNIZER="${SPEECH_RECOGNIZER:-_}"
SPEECH_MODEL="${SPEECH_MODEL:-chirp_3}"
SPEECH_LANGUAGE_CODES="${SPEECH_LANGUAGE_CODES:-ur-PK,en-US}"

gcloud run deploy "$SERVICE" \
  --source . \
  --project "$GOOGLE_CLOUD_PROJECT" \
  --region "$REGION" \
  --allow-unauthenticated \
  --set-env-vars "NODE_ENV=production,VERTEX_PROJECT_ID=$GOOGLE_CLOUD_PROJECT,VERTEX_LOCATION=$VERTEX_LOCATION,SPEECH_PROJECT_ID=$GOOGLE_CLOUD_PROJECT,SPEECH_LOCATION=$SPEECH_LOCATION,SPEECH_RECOGNIZER=$SPEECH_RECOGNIZER,SPEECH_MODEL=$SPEECH_MODEL,SPEECH_LANGUAGE_CODES=$SPEECH_LANGUAGE_CODES,GCS_BUCKET=$GCS_BUCKET,MONGO_DB_NAME=$MONGO_DB_NAME,SUPABASE_URL=$SUPABASE_URL" \
  --set-secrets "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY_SECRET:latest,FIREBASE_SERVICE_ACCOUNT_JSON=$FIREBASE_SERVICE_ACCOUNT_JSON_SECRET:latest"
